// Code generated by MockGen. DO NOT EDIT.
// Source: template.go

// Package mock_autoscaling is a generated GoMock package.
package mock_autoscaling

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	autoscaling "github.com/ionos-cloud/ionosctl/pkg/autoscaling"
)

// MockTemplatesService is a mock of TemplatesService interface.
type MockTemplatesService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplatesServiceMockRecorder
}

// MockTemplatesServiceMockRecorder is the mock recorder for MockTemplatesService.
type MockTemplatesServiceMockRecorder struct {
	mock *MockTemplatesService
}

// NewMockTemplatesService creates a new mock instance.
func NewMockTemplatesService(ctrl *gomock.Controller) *MockTemplatesService {
	mock := &MockTemplatesService{ctrl: ctrl}
	mock.recorder = &MockTemplatesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplatesService) EXPECT() *MockTemplatesServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemplatesService) Create(input autoscaling.Template) (*autoscaling.Template, *autoscaling.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", input)
	ret0, _ := ret[0].(*autoscaling.Template)
	ret1, _ := ret[1].(*autoscaling.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockTemplatesServiceMockRecorder) Create(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemplatesService)(nil).Create), input)
}

// Delete mocks base method.
func (m *MockTemplatesService) Delete(TemplateId string) (*autoscaling.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", TemplateId)
	ret0, _ := ret[0].(*autoscaling.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTemplatesServiceMockRecorder) Delete(TemplateId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemplatesService)(nil).Delete), TemplateId)
}

// Get mocks base method.
func (m *MockTemplatesService) Get(TemplateId string) (*autoscaling.Template, *autoscaling.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", TemplateId)
	ret0, _ := ret[0].(*autoscaling.Template)
	ret1, _ := ret[1].(*autoscaling.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockTemplatesServiceMockRecorder) Get(TemplateId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTemplatesService)(nil).Get), TemplateId)
}

// List mocks base method.
func (m *MockTemplatesService) List() (autoscaling.Templates, *autoscaling.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(autoscaling.Templates)
	ret1, _ := ret[1].(*autoscaling.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTemplatesServiceMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTemplatesService)(nil).List))
}
